#!/usr/bin/env sh

iwconfig $1 2>&1 | grep -q no\ wireless\ extensions\. && {
  echo Wired
  exit 0
}

essid=`nmcli -t -f active,ssid dev wifi | egrep '^yes' | cut -d':' -f2`
stngth=`nmcli -t -f active,ssid,signal dev wifi|grep yes|cut -d':' -f3`
bars=`expr $stngth / 10`

case $bars in
  0)     bar='[-----]' ;;
  1|2)   bar='[#----]' ;;
  3|4)   bar='[##---]' ;;
  5|6)   bar='[###--]' ;;
  7|8)   bar='[####-]' ;;
  9|10)  bar='[#####]' ;;
  *)     bar='[--!--]' ;;
esac

echo $essid: $stngth% $bar

exit 0
