#!/usr/bin/env bash

export PATH="$HOME/.go/bin:$PATH"

if [ $1 = "pass" ]; then
  gopass ls --flat | rofi -dmenu | xargs --no-run-if-empty gopass show -o | xdotool type --clearmodifiers --file -
elif [ $1 = "otp" ]; then
  gopass ls --flat | rofi -dmenu | xargs --no-run-if-empty gopass otp -o | tr -d "\n\r" | xdotool type --clearmodifiers --file -
elif [ $1 = "login" ]; then
  gopass ls --flat | rofi -dmenu | xargs --no-run-if-empty -I {} gopass show -o {} login | xdotool type --clearmodifiers --file -
fi
