#!/usr/bin/env python

import click
import subprocess


@click.command()
def cli():
    serverlist = subprocess.run(
        ['nvr', '--serverlist'],
        capture_output=True,
        text=True
    ).stdout.split()

    for name in serverlist:
        click.echo(f'Stopping nvim server {name}')

        result = subprocess.run(
            ['nvr', '--servername', name, '--remote-send', "'<Esc>:wqa<CR>'"],
            capture_output=True,
            text=True
        )
        if result.returncode > 0:
            click.echo(f'Vim server {name} failed to stop:')
            click.echo(result.stdout)

if __name__ == '__main__':
    cli()
